---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
        - recipe[met-server::default]
        - recipe[met-solr::zookeeper]
        - recipe[met-solr::default]
    attributes: {
        "met-solr": {
            "solr": {
                "enable_cloud": true
            }
        }
    }
