name             'met-solr'
maintainer       'Espen Myrland'
maintainer_email 'espenm@met.no'
license          'All rights reserved'
description      'Installs/Configures met-solr'
long_description 'Installs/Configures met-solr'
version          '0.3.7'

depends 'java'
depends 'met-server',   '>= 0.52.2'
